[tvalue]
"source path" = "/home/akado/Documents/Git/Flawlesse/ISP_Labs/lab2/dumpings/string.json"
"target path" = "/home/akado/Documents/Git/Flawlesse/ISP_Labs/lab2/dumpings/"
"new extension" = "toml"

